apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rc-backend
  labels:
    tier: rc-backend
spec:
  template:
    metadata:
      name: backend-pod
      labels:
        app: backend
    spec:
      containers:
        - name: nginx-backend-server-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      app: backend
